'use strict';

const ActionTypes = {
  RECIEVE_CONFIGURATIONS:         'RECIEVE_CONFIGURATIONS',
  RECIEVE_CONFIGURATION_DETAILS:  'RECIEVE_CONFIGURATION_DETAILS',
  RECIEVE_CONFIGURATIONS_ERROR:   'RECIEVE_CONFIGURATIONS_ERROR',
  RECIEVE_CONFIGURATION_ERROR:    'RECIEVE_CONFIGURATION_ERROR'
};

export default ActionTypes;
