'use strict';

const ActionTypes = {
  RECIEVE_CONFIGURATIONS:         'RECIEVE_CONFIGURATIONS',
  RECIEVE_CONFIGURATION_DETAILS:  'RECIEVE_CONFIGURATION_DETAILS',
  RECIEVE_CONFIGURATIONS_ERROR:   'RECIEVE_CONFIGURATIONS_ERROR',
  RECIEVE_CONFIGURATION_ERROR:    'RECIEVE_CONFIGURATION_ERROR',


  /**
   * Categories
   */

  FETCH_CATEGORY: 'FETCH_CATEGORY',
  FETCH_CATEGORY_SUCCESS: 'FETCH_CATEGORY_SUCCESS',
  FETCH_CATEGORY_ERROR: 'FETCH_CATEGORY_ERROR'

};

export default ActionTypes;
