'use strict';

const ActionTypes = {
  SENT_EVENTS_REQUEST:  'SENT_EVENTS_REQUEST',
  RECIEVE_EVENTS:       'RECIEVE_EVENTS',
  RECIEVE_EVENTS_ERROR: 'RECIEVE_EVENTS_ERROR',
  RECIEVE_EVENTS:       'RECIEVE_EVENT',
  RECIEVE_EVENT_ERROR:  'RECIEVE_EVENT_ERROR'
};

export default ActionTypes;
