'use strict';

const ActionTypes = {
  ORDER_Wizard_SELECT_CONFIGURATION: 'ORDER_Wizard_SELECT_CONFIGURATION',
  ORDER_Wizard_REMOVE_SELECT_EVENT: 'ORDER_Wizard_REMOVE_SELECT_EVENT',
  ORDER_WIZARD_RECIVE_CONFIGURATION_DETAILS: 'ORDER_WIZARD_RECIVE_CONFIGURATION_DETAILS',
  ORDER_Wizard_REMOVE_FROM_RENTED: 'ORDER_Wizard_REMOVE_FROM_RENTED',
  ORDER_Wizard_ADD_TO_RENTED: 'ORDER_Wizard_ADD_TO_RENTED',
  ORDER_Wizard_EMPTY_SELECTION: 'ORDER_Wizard_EMPTY_SELECTION',
  ORDER_Wizard_CATEGORY_ALL_STOCK_ITEM: 'ORDER_Wizard_CATEGORY_ALL_STOCK_ITEM',
  ORDER_Wizard_SELECTED_OPTION: 'ORDER_Wizard_SELECTED_OPTION',
  ORDER_Wizard_RENTAL_FILTER: 'ORDER_Wizard_RENTAL_FILTER',
  ORDER_WIZARD_RECIVE_CATEGORIES_FOR_STOCK: 'ORDER_WIZARD_RECIVE_CATEGORIES_FOR_STOCK',
  ORDER_Wizard_CATEGORY_STOCK_ITEM: 'ORDER_Wizard_CATEGORY_STOCK_ITEM',
  ORDER_Wizard_RENTAL_MODAL_STATE: 'ORDER_Wizard_RENTAL_MODAL_STATE',
  ORDER_Wizard_UPDATE_RENTAL_MODAL_STATE: 'ORDER_Wizard_UPDATE_RENTAL_MODAL_STATE',
  ORDER_Wizard_UPDATE_RESERVED_FROM_INVENTORY: 'ORDER_Wizard_UPDATE_RESERVED_FROM_INVENTORY',

  /**
   * Constants for Order Store EVENTS.
   *
   */

  ORDER_Wizard_SELECT_EVENT:         'ORDER_Wizard_SELECT_EVENT',
  ORDER_Wizard_SELECT_EVENT_SUCCESS: 'ORDER_Wizard_SELECT_EVENT_SUCCESS',
  ORDER_Wizard_SELECT_EVENT_ERROR:   'ORDER_Wizard_SELECT_EVENT_ERROR',


  /**
   * Constants for CHECK AVAILABILITY
   *
   */
  ORDER_Wizard_CHECK_AVAILABILITY:         'ORDER_WIZARD_CHECK_AVAILABILITY',
  ORDER_Wizard_CHECK_AVAILABILITY_SUCCESS: 'ORDER_WIZARD_CHECK_AVAILABILITY_SUCCESS',
  ORDER_Wizard_CHECK_AVAILABILITY_ERROR:   'ORDER_WIZARD_CHECK_AVAILABILITY_ERROR',
  ORDER_Wizard_RENT_NECESSARY:             'ORDER_Wizard_RENT_NECESSARY'

};

export default ActionTypes;
