'use strict';

const ActionTypes = {
  ORDER_WIZZARD_SELECT_CONFIGURATION: 'ORDER_WIZZARD_SELECT_CONFIGURATION',
  ORDER_WIZZARD_REMOVE_SELECT_EVENT: 'ORDER_WIZZARD_REMOVE_SELECT_EVENT',
  ORDER_WIZARD_RECIVE_CONFIGURATION_DETAILS: 'ORDER_WIZARD_RECIVE_CONFIGURATION_DETAILS',
  ORDER_WIZZARD_REMOVE_FROM_RENTED: 'ORDER_WIZZARD_REMOVE_FROM_RENTED',
  ORDER_WIZZARD_ADD_TO_RENTED: 'ORDER_WIZZARD_ADD_TO_RENTED',
  ORDER_WIZZARD_EMPTY_SELECTION: 'ORDER_WIZZARD_EMPTY_SELECTION',
  ORDER_WIZZARD_CATEGORY_STOCK_ITEM: 'ORDER_WIZZARD_CATEGORY_STOCK_ITEM',
  ORDER_WIZZARD_SELECTED_OPTION: 'ORDER_WIZZARD_SELECTED_OPTION',

  /**
   * Constants for Order Store EVENTS.
   *
   */

  ORDER_WIZZARD_SELECT_EVENT:         'ORDER_WIZZARD_SELECT_EVENT',
  ORDER_WIZZARD_SELECT_EVENT_SUCCESS: 'ORDER_WIZZARD_SELECT_EVENT_SUCCESS',
  ORDER_WIZZARD_SELECT_EVENT_ERROR:   'ORDER_WIZZARD_SELECT_EVENT_ERROR',


  /**
   * Constants for CHECK AVAILABILITY
   *
   */
  ORDER_WIZZARD_CHECK_AVAILABILITY:         'ORDER_WIZARD_CHECK_AVAILABILITY',
  ORDER_WIZZARD_CHECK_AVAILABILITY_SUCCESS: 'ORDER_WIZARD_CHECK_AVAILABILITY_SUCCESS',
  ORDER_WIZZARD_CHECK_AVAILABILITY_ERROR:   'ORDER_WIZARD_CHECK_AVAILABILITY_ERROR',
  ORDER_WIZZARD_RENT_NECESSARY:             'ORDER_WIZZARD_RENT_NECESSARY'

};

export default ActionTypes;
