'use strict';

const ActionTypes = {
  RECIEVE_ORDERS:       'RECIEVE_ORDERS',
  RECIEVE_ORDERS_ERROR: 'RECIEVE_ORDERS_ERROR',
  RECIEVE_ORDER:        'RECIEVE_ORDER',
  RECIEVE_ORDER_ERROR:  'RECIEVE_ORDER_ERROR',
  RECIEVE_ORDER_PROBLEMS: 'RECIEVE_ORDER_PROBLEMS',
  RECIEVE_ORDER_PROBLEMS_ERROR: 'RECIEVE_ORDER_PROBLEMS_ERROR',
  ORDER_POSTED: 'ORDER_POSTED'
};

export default ActionTypes;
